### ISSUE TITLE
异常退出，不给？

### ISSUE THREAD

**Issue by zhanjuzhang** [40t/go-sniffer#4]
panic: runtime error: index out of range

goroutine 7 [running]:
github.com/40t/go-sniffer/plugSrc/mysql/build.(*stream).resolveServerPacket(0xc420056d80, 0xc4204cd000, 0x0, 0x200, 0xb)
	/data/go/src/github.com/40t/go-sniffer/plugSrc/mysql/build/entry.go:219 +0x442
github.com/40t/go-sniffer/plugSrc/mysql/build.(*stream).resolve(0xc420056d80)
	/data/go/src/github.com/40t/go-sniffer/plugSrc/mysql/build/entry.go:194 +0xc0
created by github.com/40t/go-sniffer/plugSrc/mysql/build.(*Mysql).ResolveStream
	/data/go/src/github.com/40t/go-sniffer/plugSrc/mysql/build/entry.go:71 +0x3b8

**Comment by 40t** [comment]
最近事情比较多，我会在一周以内处理此问题
